title: "{$sep}-=( {$p}Настройки чемпиона {$sep})=-"
type: HOPPER
sound: ITEM_ARMOR_EQUIP_DIAMOND

options:
  upgrade:
    name: "&bМодернизация оборудования"
    material: DIAMOND_CHESTPLATE
    lore:
      - "{$sep}Улучшает"
      - "броню и оружие вашего чемпиона с каждым улучшением."
      - ""
      - "{$p}Уровень{$colon} {$s}%level%"
      - "{$p}Стоимость{$colon} {$s}%cost%"
    slot: 0
  change:
    name: "{$s}Изменять"
    material: DIAMOND_SWORD
    lore:
      - "{$sep}Измените тип своего чемпиона."
    slot: 1

  back:
    name: "{$p}Назад"
    material: BARRIER
    lore:
      - "{$s}Вернитесь к улучшениям чемпионов."
    slot: 4