main: org.kingdoms.peacetreaties.PeaceTreatiesAddon
name: "${project.name}"
description: "${project.description}"
author: Crypto Morin
version: "${project.version}"
api-version: "1.13"
folia-supported: true
depend: [ Kingdoms ]