title: "{$sep}-=( {$sep}Cài đặt {$sep})=-"
rows: 6
sound: ITEM_BOOK_PAGE_TURN

options:
  back:
    posx: 1
    posy: 1
    material: PLAYER_HEAD
    name: '{$p}Quay lại'
    lore: [ '{$s}Quay lại menu nexus.' ]
    skull: "{$gui-back}"
  light-blue-stained-glass-pane:
    slots: [ 1, 2, 6, 7, 8, 9, 17, 18, 21, 23, 26, 27, 29, 30, 32, 33, 35, 36, 39, 41, 44, 45, 53 ]
    material: LIGHT_BLUE_STAINED_GLASS_PANE
    name: ''
  upgrade:
    posx: 5
    posy: 4
    material: NETHER_STAR
    upgrade:
      condition: "level < max_level"
      name: "{$sp}Nâng cấp{$colon} {$s}%roman@level% {$arrow} {$s}%roman@next_level%"
      material: NETHER_STAR
      lvl-I:
        condition: 'level == 1'
        lore: |
          {$dot} {$p}&lNâng cấp linh tinh{$colon}
            {$sdot} {$s}Mở khóa Insanity

          {$dot} {$p}&lPowerups{$colon}
            {$sdot} {$s}Tất cả nâng cấp{$colon} {$sp}{$lvlup} Cấp. 30

          {$dot} {$p}&lNâng cấp Nhà vô địch{$colon}
            {$sdot} {$s}Mở khóa Throw
            {$sdot} {$s}Mở khóa Damage Cap
            {$sdot} {$s}Máu{$colon} {$sp}{$lvlup} Cấp. 30

          {$dot} {$p}&lTháp pháo{$colon}
            {$sdot} {$s}Mở khóa Tháp pháo Hồi máu
            {$sdot} {$s}Mở khóa Tháp pháo Lửa

          {$dot} {$p}&lCấu trúc{$colon}
            {$sdot} {$s}Mở khóa Powercell
            {$sdot} {$s}Mở khóa Tiền đồn

          {$p}Cấp độ tối đa{$colon} {$s}%roman@max_level%
          {$p}Chi phí{$colon} {$s}%fancy@upgrade_cost%
      lvl-II:
        condition: 'level == 2'
        lore: |
          {$dot} {$p}&lNâng cấp linh tinh{$colon}
            {$sdot} {$s}Mở khóa Lính canh
            {$sdot} {$s}Mở khóa Vinh quang
            {$sdot} {$s}Mở khóa Giữ kho đồ

          {$dot} {$p}&lPowerups{$colon}
            {$sdot} {$s}Tất cả nâng cấp{$colon} {$sp}{$lvlup} Cấp. 40

          {$dot} {$p}&lNâng cấp Nhà vô địch{$colon}
            {$sdot} {$s}Mở khóa Drag
            {$sdot} {$s}Mở khóa Thor
            {$sdot} {$s}Máu{$colon} {$sp}{$lvlup} Cấp. 40

          {$dot} {$p}&lTháp pháo{$colon}
            {$sdot} {$s}Mở khóa Tháp pháo Tâm linh
            {$sdot} {$s}Mở khóa Tháp pháo Hỏa ngục

          {$dot} {$p}&lCấu trúc{$colon}
            {$sdot} {$s}Mở khóa Máy khai thác

          {$p}Cấp độ tối đa{$colon} {$s}%roman@max_level%
          {$p}Chi phí{$colon} {$s}%fancy@upgrade_cost%
      lvl-III:
        condition: 'level == 3'
        lore: |
          {$dot} {$p}&lNâng cấp linh tinh{$colon}
            {$sdot} {$s}Mở khóa Lính canh Nexus
            {$sdot} {$s}Giữ kho đồ{$colon}: {$sp}{$lvlup} Cấp. 2

          {$dot} {$p}&lPowerups{$colon}
            {$sdot} {$s}Tất cả nâng cấp{$colon} {$sp}{$lvlup} Cấp. 50

          {$dot} {$p}&lNâng cấp Nhà vô địch{$colon}
            {$sdot} {$s}Mở khóa Gia cố

          {$dot} {$p}&lTháp pháo{$colon}
            {$sdot} {$s}Mở khóa Tháp pháo Tia nhiệt
            {$sdot} {$s}Mở khóa Tháp pháo Lính

          {$dot} {$p}&lCấu trúc{$colon}
            {$sdot} {$s}Mở khóa Cấu trúc Bệ dịch chuyển
            {$sdot} {$s}Mở khóa Cấu trúc Bộ điều chỉnh

          {$p}Cấp độ tối đa{$colon} {$s}%roman@max_level%
          {$p}Chi phí{$colon} {$s}%fancy@upgrade_cost%
      lvl-IV:
        condition: 'level == 4'
        lore: |
          {$dot} {$p}&lNâng cấp linh tinh{$colon}
            {$sdot} {$s}Mở khóa Bay
            {$sdot} {$s}Giữ kho đồ{$colon}: {$sp}{$lvlup} Cấp. 3

          {$dot} {$p}&lPowerups{$colon}
            {$sdot} {$s}Tất cả nâng cấp{$colon} {$sp}{$lvlup} Cấp. 70

          {$dot} {$p}&lNâng cấp Nhà vô địch{$colon}
            {$sdot} {$s}Mở khóa Burst

          {$dot} {$p}&lTháp pháo{$colon}
            {$sdot} {$s}Mở khóa Tháp pháo Hỏa ngục

          {$dot} {$p}&lCấu trúc{$colon}
            {$sdot} {$s}Mở khóa Pháo Công Thành

          {$p}Cấp độ tối đa{$colon} {$s}%roman@max_level%
          {$p}Chi phí{$colon} {$s}%fancy@upgrade_cost%
      else:
        lore: [ "&cNâng cấp Vương quốc không xác định: %level%" ]
    maxxed:
      name: "{$sp}Cấp độ Vương quốc{$colon} {$s}%roman@level% {$sep}(&5Tối đa{$sep})"
      material: NETHER_STAR
  public-home:
    posx: 4
    posy: 1
    material: DARK_OAK_DOOR
    name: "{$s}Nhà công khai{$colon} %bool@kingdoms_kingdom_home_is_public%"
    lore: |
      {$sep}Khi nhà của bạn là công khai, bất kỳ ai
      cũng có thể dịch chuyển đến đó bằng
      {$p}/k home %kingdoms_kingdom_name%

      {$p}Nhấp chuột trái {$sep}để chuyển đổi nhà công khai.
      {$p}Nhấp chuột phải {$sep}để đặt chi phí nhà công khai.
      Chi phí này chỉ dành cho những người bên ngoài
      vương quốc của bạn.
      {$p}Thuế nhà hiện tại{$colon} {$s}%kingdoms_kingdom_taxes_home%

      {$note} Cả hai vương quốc cần phải có
      thuộc tính quan hệ HOME để
      mối quan hệ của bạn hoạt động.
  hidden:
    posx: 5
    posy: 1
    material: POTION
    color: 818595
    name: "{$s}Ẩn{$colon} %bool@kingdoms_kingdom_is_hidden%"
    lore: |
      {$sep}Các vương quốc ẩn không được hiển thị
      trong {$p}/k map {$sep}và bản đồ trực tuyến.
  tax:
    posx: 6
    posy: 1
    material: PAPER
    name: '{$s}Thuế'
    lore: |
      {$sep}Thay đổi thuế vương quốc của bạn
      đối với thành viên.

      {$s}Phương trình thuế thành viên{$colon}
      {$p}%tax_equation%
      {$s}Thuế cá nhân của bạn{$colon} {$p}$%fancy@kingdoms_tax%

      {$s}Thuế vương quốc{$colon} {$p}$%fancy@kingdoms_kingdom_tax%
  blue-stained-glass-pane:
    slots: [ 10, 11, 12, 13, 14, 15, 16, 19, 25, 28, 34, 37, 43, 46, 47, 48, 49, 50, 51, 52 ]
    material: BLUE_STAINED_GLASS_PANE
    name: ''
  relations:
    posx: 3
    posy: 3
    material: WRITABLE_BOOK
    name: '{$s}Quan hệ'
    lore: |
      {$sep}Thay đổi các thuộc tính quan hệ của bạn
      cho các vương quốc khác.

      {$sep}[&e!{$sep}] {$es}Để một số thuộc tính hoạt động,
      cả hai vương quốc cần phải bật thuộc tính đó
      cho mối quan hệ.

      Ví dụ, nếu bạn có thuộc tính {$e}BUILD {$es}được bật
      cho đồng minh, nhưng bạn đang cố gắng
      xây dựng trên đất của đồng minh mà không có
      thuộc tính {$e}BUILD {$es}được bật cho đồng minh,
      điều này sẽ không hoạt động. Họ cũng sẽ không thể
      xây dựng trên đất của bạn.
  banners:
    posx: 5
    posy: 3
    material: BLACK_BANNER
    name: '{$s}Cờ hiệu & Biểu ngữ'
    lore: |
      {$sep}Đặt cờ hiệu và biểu ngữ vương quốc của bạn
      cho bản đồ web trực tuyến, biểu tượng, và chúng có thể
      cũng xuất hiện ở những nơi khác như các khối trang trí
      và một biểu tượng của vương quốc của bạn.
  pacifism:
    posx: 7
    posy: 3
    material: END_CRYSTAL
    name: '{$s}Hòa bình{$colon} %bool@kingdoms_kingdom_is_pacifist%'
    lore: |
      {$sep}Khi bạn ở chế độ hòa bình,
      vương quốc của bạn không thể xâm lược
      và không thể bị các vương quốc khác xâm lược.

      Nếu bạn xâm lược một Vương quốc, bạn không thể trở lại
      chế độ hòa bình trong một tuần.
      {? pacifism_left > 0 ? "
      {$p}Thời gian hồi chiêu{$colon} {$s}%pacifism_cooldown%" }
  invites:
    posx: 3
    posy: 5
    material: BOOK
    name: '{$s}Yêu cầu Mời{$colon} %bool@kingdoms_kingdom_requires_invite%'
    lore: |
      {$sep}Khi tắt, bất kỳ ai cũng có thể
      tham gia vương quốc này mà không cần
      một lời mời với {$p}/k join %kingdoms_kingdom_name%
  color:
    posx: 5
    posy: 5
    material: LIME_DYE
    name: '{$s}Màu sắc{$colon} &c%r%{$sep}, {$p}%g%{$sep}, {$sp}%b% {$sep}(%hex@kingdoms_kingdom_color%%kingdoms_kingdom_color%{$sep})'
    lore: |
      {$sep}Đặt màu đánh dấu vương quốc của bạn
      cho trò chuyện và bản đồ đất trực tuyến.
  shields:
    posx: 7
    posy: 5
    material: SHIELD
    name: '{$s}Lá chắn{$colon} {$p}%time@kingdoms_shield_time_left%'
    lore: |
      {$sep}Mua một lá chắn cho
      vương quốc của bạn để bảo vệ vương quốc của bạn
      chống lại các cuộc xâm lược.