title: "&cCài đặt Bản đồ"
type: HOPPER

options:
  scoreboard:
    slot: 0
    material: PAPER
    lore: |
      {$sep}Hiển thị bản đồ vương quốc dưới dạng bảng điểm
      tiện lợi hơn nhiều so với
      chế độ bản đồ tự động và tự động cập nhật.

      Nhược điểm là nó
      chiếm một phần lớn màn hình của bạn
      và bạn phải ghi nhớ các biểu tượng và
      màu sắc và ý nghĩa của chúng.

      Tùy chọn này sẽ đặt lại nếu bạn rời đi.
    enabled:
      condition: scoreboard_enabled
      name: "{$enabled} Bật/Tắt Bảng điểm"
      glow: true
    else:
      name: "{$disabled} Bật/Tắt Bảng điểm"
  reset:
    slot: 1
    material: PLAYER_HEAD
    name: '&4Đặt lại Cài đặt'

    # https://minecraft-heads.com/custom-heads/alphabet/45282-redstone-block-refresh
    skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzA1ZWI3ZTA0ODg2ODMyNTRlZGI2NzgyYzVkYjhkMjdjZDA3OGU3ODRkZTJkY2RjZDI1Y2UwODY0ZGZhYmQzOCJ9fX0='
  resize:
    slot: 2
    material: PLAYER_HEAD
    name: '{$p}Thay đổi kích thước'
    lore:
      - "{$sep}Thay đổi kích thước &achiều rộng {$sep}và &achiều cao bản đồ của bạn"
      - "{$sep}Kích thước hiện tại của bạn{$colon} {$p}%kingdoms_map_width%{$sep}, {$p}%kingdoms_map_height%"

    # https://minecraft-heads.com/custom-heads/decoration/49973-globe
    skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODc5ZTU0Y2JlODc4NjdkMTRiMmZiZGYzZjE4NzA4OTQzNTIwNDhkZmVjZDk2Mjg0NmRlYTg5M2IyMTU0Yzg1In19fQ=='
  auto:
    slot: 3
    material: PLAYER_HEAD
    lore:
      - "{$sep}Bản đồ tự động xuất hiện"
      - "khi bạn đi đến các vùng đất khác nhau."

    enabled:
      condition: 'auto_map_enabled'
      name: "{$enabled} Tự động"
      # https://minecraft-heads.com/custom-heads/alphabet/21774-green-checkmark
      skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDMxMmNhNDYzMmRlZjVmZmFmMmViMGQ5ZDdjYzdiNTVhNTBjNGUzOTIwZDkwMzcyYWFiMTQwNzgxZjVkZmJjNCJ9fX0='
    else:
      name: "{$disabled} Tự động"
      # https://minecraft-heads.com/custom-heads/miscellaneous/44761-x
      skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5miW5lY3JhZnQubmV0L3RleHR1cmUvZDdhY2ZmNThjMjExZTQ2ODA2ZDRhYzlhNzczMjBiZjU3MjUwZWQ4YmY3OTMzZWE0M2FjOGVmMmZkNzBkZWZkYyJ9fX0='
  gui:
    slot: 4
    material: CHEST
    name: "{$p}Xem bản đồ trong GUI"
    lore: |
      {$sep}Ưu điểm là hành vi nhấp chuột
      tốt hơn và các biểu tượng
      rõ ràng hơn cho các vùng đất khác nhau.

      Nhược điểm là giới hạn
      kích thước kho đồ GUI
      và hạn chế khả năng di chuyển của bạn.