title: "{$sep}-=( {$sep}Settings {$sep})=-"
rows: 6
sound: ITEM_BOOK_PAGE_TURN

options:
  back:
    posx: 1
    posy: 1
    material: PLAYER_HEAD
    name: '{$p}Back'
    lore: [ '{$s}Go back to nexus menu.' ]
    skull: "{$gui-back}"
  light-blue-stained-glass-pane:
    slots: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 21, 23, 26, 27, 29, 30, 31, 32, 33, 35, 36, 39, 41, 44, 45, 53 ]
    material: LIGHT_BLUE_STAINED_GLASS_PANE
    name: ''
  public-home:
    posx: 3
    posy: 5
    material: DARK_OAK_DOOR
    name: "{$s}Public Home{$colon} %bool@kingdoms_nation_home_is_public%"
    lore: |
      {$sep}When your home is public, anyone
      can teleport to it using
      {$p}/k nation home %kingdoms_nation_name%
  tax:
    posx: 7
    posy: 5
    material: PAPER
    name: '{$s}Tax'
    lore: |
      {$sep}Change your nation taxes
      for members.

      {$s}Member Tax Equation{$colon}
      {$p}%tax_equation%
      {$s}Your Member Tax{$colon} {$p}$%fancy@kingdoms_nation_tax%

      {$s}Nation Server Tax{$colon} {$p}$%fancy@kingdoms_nation_tax%
  blue-stained-glass-pane:
    slots: [ 10, 11, 12, 13, 14, 15, 16, 19, 25, 28, 34, 37, 43, 46, 47, 48, 49, 50, 51, 52 ]
    material: BLUE_STAINED_GLASS_PANE
    name: ''
  relations:
    posx: 3
    posy: 3
    material: WRITABLE_BOOK
    name: '{$s}Relations'
    lore: |
      {$sep}Change your relation attributes
      for other nations.

      {$sep}[&e!{$sep}] {$es}In order for some attributes
      to work, both kingdoms need to have the
      attribute enabled for the relationship.

      For example, if you have the {$e}BUILD {$es}attribute
      enabled for allies, and then try to
      build in an ally's land that doesn't also
      have the same attribute enabled for allies,
      it won't work. Said ally won't be able to
      build in your land either.
  banners:
    posx: 5
    posy: 3
    material: BLACK_BANNER
    name: '{$s}Flag'
    lore: |
      {$sep}Set your nation's flag for online maps.
      Click to see your flag URL.
      This won't update the map instantly.
  color:
    posx: 5
    posy: 5
    material: LIME_DYE
    name: '{$s}Color{$colon} &c%r%{$sep}, {$p}%g%{$sep}, {$sp}%b% {$sep}(%hex@kingdoms_nation_color%%kingdoms_nation_color%{$sep})'
    lore: |
      {$sep}Set your nation marker
      color for chat and online land maps.
  shields:
    posx: 7
    posy: 3
    material: SHIELD
    name: '{$s}Shield{$colon} {$p}%time@kingdoms_nation_shield_time_left%'
    lore: |
      {$sep}Buy a shield for your
      nation to protect your kingdom
      against invades.

      Kingdom members who invade when
      nation shields are enabled, will
      temporarily lose access to nation's
      shield.