title: "{$sep}-=( {$sep}Beállítások {$sep})=-"
rows: 6
sound: ITEM_BOOK_PAGE_TURN

options:
  back:
    posx: 1
    posy: 1
    material: PLAYER_HEAD
    name: '{$p}Vissza'
    lore: [ '{$s}Vissza a nexus menübe.' ]
    skull: "{$gui-back}"
  light-blue-stained-glass-pane:
    slots: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 21, 23, 26, 27, 29, 30, 31, 32, 33, 35, 36, 39, 41, 44, 45, 53 ]
    material: LIGHT_BLUE_STAINED_GLASS_PANE
    name: ''
  public-home:
    posx: 3
    posy: 5
    material: DARK_OAK_DOOR
    name: "{$s}Nyilvános otthon{$colon} %kingdoms_bool_nation_home_is_public%"
    lore: |
      {$sep}Amikor nyilvános az otthonod,
      bárki odateleportálhat használva
      a {$p}/k nation home %kingdoms_nation_name%
      {$sep}parancsot.
  tax:
    posx: 7
    posy: 5
    material: PAPER
    name: '{$s}Adó'
    lore: |
      {$sep}Nemzeted adóinak
      változtatása a tagok számára.

      {$s}Tagság adóegyenlet{$colon}
      {$p}%tax_equation%
      {$s}Tagságod adója{$colon} {$p}$%fancy@kingdoms_nation_tax%

      {$s}Nemzet kiszólgáló adó{$colon} {$p}$%fancy@kingdoms_nation_tax%
  blue-stained-glass-pane:
    slots: [ 10, 11, 12, 13, 14, 15, 16, 19, 25, 28, 34, 37, 43, 46, 47, 48, 49, 50, 51, 52 ]
    material: BLUE_STAINED_GLASS_PANE
    name: ''
  relations:
    posx: 3
    posy: 3
    material: WRITABLE_BOOK
    name: '{$s}Kapcsolatok'
    lore: |
      {$sep}Más nemzetekhez köthető kpcsolati
      attribútumaid megváltoztatása.

      {$sep}[&e!{$sep}] {$es}Egyes attribútumok
      működéséhez mindkét királyságban
      szükséges engedélyezni az attribútumokat
      a kapcsolathoz.
      
      Például ha az {$e}ÉPÍTÉS {$es}attribútum
      engedélyezve van a szövetségesid
      számára, de egy olyan szövetséges
      földjére próbálsz építeni, akinél
      nincs engedélyezve az {$e}ÉPÍTÉS 
      {$es}attribútum a szövetségeseinek,
      akkor nem fog működni, nem fogsz tudni
      a területen építeni.
  banners:
    posx: 5
    posy: 3
    material: BLACK_BANNER
    name: '{$s}Zászló'
    lore: |
      {$sep}Állítsd be a nemzeted zászlóját az
      online térképekhez. Klikk a zászló
      URL-jének megtekintéséhez.
      Ez nem frissíti azonnal a térképet.
  color:
    posx: 5
    posy: 5
    material: LIME_DYE
    name: '{$s}Szín{$colon} &c%r%{$sep}, {$p}%g%{$sep}, {$sp}%b% {$sep}(%hex@kingdoms_nation_color%%kingdoms_nation_color%{$sep})'
    lore: |
      {$sep}Állítsd be a nemzeted
      jelölőszínét a csevegéshez
      és az online földtérképekhez.
  shields:
    posx: 7
    posy: 3
    material: SHIELD
    name: '{$s}Pajzs{$colon} {$p}%time@kingdoms_nation_shield_time_left%'
    lore: |
      {$sep}Vásárolj pajzsot a nemzeted
      védelmére, hogy megvédd az
      ostromok ellen a királyságodat.
      
      Azok a királysági tagok, akik
      akkor támadnak, amikor a nemzet
      pajzsai engedélyezve vannak,
      átmenetileg elveszítik a nemzet
      pajzsához való hozzáférést.
