title: "{$sep}-=( {$p}Cài đặt Nhà vô địch {$sep})=-"
type: HOPPER
sound: ITEM_ARMOR_EQUIP_DIAMOND

options:
  upgrade:
    name: "&bNâng cấp Trang bị"
    material: DIAMOND_CHESTPLATE
    lore:
      - "{$sep}Cải thiện giáp và vũ khí của nhà vô địch"
      - "của bạn với mỗi lần nâng cấp."
      - ""
      - "{$p}Cấp độ{$colon} {$s}%level%"
      - "{$p}Chi phí{$colon} {$s}%cost%"
    slot: 0
  change:
    name: "{$s}Thay đổi"
    material: DIAMOND_SWORD
    lore:
      - "{$sep}Thay đổi loại nhà vô địch của bạn."
    slot: 1

  back:
    name: "{$p}Quay lại"
    material: BARRIER
    lore:
      - "{$s}Quay lại phần nâng cấp nhà vô địch."
    slot: 4