title: "{$sep}-=( {$p}Bajnok beállításai {$sep})=-"
type: HOPPER
sound: ITEM_ARMOR_EQUIP_DIAMOND

options:
  upgrade:
    name: "&bFelszerelés fejlesztése"
    material: DIAMOND_CHESTPLATE
    lore:
      - "{$sep}A fejlesztés tökéletesíti a"
      - "bajnokod páncélját és fegyverét."
      - ""
      - "{$p}Szint{$colon} {$s}%level%"
      - "{$p}Költség{$colon} {$s}%cost%"
    slot: 0
  change:
    name: "{$s}Csere"
    material: DIAMOND_SWORD
    lore:
      - "{$sep}A bajnok típusának cseréje."
    slot: 1

  back:
    name: "{$p}Vissza"
    material: BARRIER
    lore:
      - "{$s}Vissza a bajnok fejlesztéséhez."
    slot: 4