title: "&cConfigurações do Mapa"
type: HOPPER
options:
  scoreboard:
    slot: 0
    material: PAPER
    lore: |
      {$sep}Mostra o mapa do reino como um placar, que é muito mais conveniente do que o modo de mapa automático e se atualiza automaticamente.

      A desvantagem é que ocupa uma grande parte da sua tela e você deve memorizar os símbolos e as cores e o que eles significam.

      Essa opção é redefinida se você sair.
    enabled:
      condition: scoreboard_enabled
      name: "{$enabled} Alternar Placar"
      glow: true
    else:
      name: "{$disabled} Alternar Placar"
  reset:
    slot: 1
    material: PLAYER_HEAD
    name: '&4Redefinir Configurações'
    #https://minecraft-heads.com/custom-heads/alphabet/45282-redstone-block-refresh
    skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzA1ZWI3ZTA0ODg2ODMyNTRlZGI2NzgyYzVkYjhkMjdjZDA3OGU3ODRkZTJkY2RjZDI1Y2UwODY0ZGZhYmQzOCJ9fX0='
  resize:
    slot: 2
    material: PLAYER_HEAD
    name: '{$p}Redimensionar'
    lore:
      - "{$sep}Resize your own map &awidth {$sep}and &aheight"
      - "{$sep}Your current size{$colon} {$p}%kingdoms_map_width%{$sep}, {$p}%kingdoms_map_height%"
    #https://minecraft-heads.com/custom-heads/decoration/49973-globe
    skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODc5ZTU0Y2JlODc4NjdkMTRiMmZiZGYzZjE4NzA4OTQzNTIwNDhkZmVjZDk2Mjg0NmRlYTg5M2IyMTU0Yzg1In19fQ=='
  auto:
    slot: 3
    material: PLAYER_HEAD
    lore:
      - "{$sep}The map keeps appearing automatically"
      - "as you walk to different lands."
    enabled:
      condition: 'auto_map_enabled'
      name: "{$enabled} Automático"
      #https://minecraft-heads.com/custom-heads/alphabet/21774-green-checkmark
      skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDMxMmNhNDYzMmRlZjVmZmFmMmViMGQ5ZDdjYzdiNTVhNTBjNGUzOTIwZDkwMzcyYWFiMTQwNzgxZjVkZmJjNCJ9fX0='
    else:
      name: "{$disabled} Automático"
      #https://minecraft-heads.com/custom-heads/miscellaneous/44761-x
      skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDdhY2ZmNThjMjExZTQ2ODA2ZDRhYzlhNzczMjBiZjU3MjUwZWQ4YmY3OTMzZWE0M2FjOGVmMmZkNzBkZWZkYyJ9fX0='
  gui:
    slot: 4
    material: CHEST
    name: "{$p}Veja o mapa em uma Interface"
    lore: |
      {$sep}As vantagens seriam um comportamento de clique melhor e ícones mais claros para diferentes terras.

      As desvantagens seriam o limite do tamanho do inventário da GUI e a limitação da sua mobilidade.
